name: Latest OTD build

on:
  # schedule:
  #   - cron:  '0 5 * * 1'
  workflow_dispatch:

jobs:
  Build:
    strategy:
      matrix:
        include:
          - plugin: BezierInterpolator
          - plugin: RadialFollow
          - plugin: TouchTapping
          - plugin: SinCursor

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Get latest OTD
      run: |
         git submodule update --init --force --remote --merge
         echo "OTD_sha=$(git submodule status | cut -c 2-8)" >> $GITHUB_ENV

    - name: Setup dotnet
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '6.0.x'

    - name: Publish
      env:
        plugin: ${{ matrix.plugin }}
      run: dotnet publish $plugin --configuration Release -f net6.0 -p:DebugType=embedded -o ./build/

    - name: Upload binaries
      uses: actions/upload-artifact@main
      with:
        name: ${{ format('{0} OTD_{1}', matrix.plugin, env.OTD_sha) }}
        path: |
          ./build/*.dll
          !./build/*.json
          !./build/OpenTabletDriver.Plugin.dll
